# Generated by Django 5.1.3 on 2024-11-20 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direccion_envio", models.CharField(blank=True, max_length=200)),
                ("ciudad_envio", models.CharField(blank=True, max_length=100)),
                ("codigo_postal_envio", models.CharField(blank=True, max_length=10)),
                ("direccion_facturacion", models.CharField(blank=True, max_length=200)),
                ("ciudad_facturacion", models.CharField(blank=True, max_length=100)),
                (
                    "codigo_postal_facturacion",
                    models.CharField(blank=True, max_length=10),
                ),
                ("telefono", models.CharField(blank=True, max_length=15)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
