# Generated by Django 5.1.3 on 2024-11-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="ciudad",
            new_name="ciudad_envio",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="codigo_postal",
            new_name="codigo_postal_envio",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="direccion",
            new_name="direccion_envio",
        ),
        migrations.AddField(
            model_name="profile",
            name="misma_direccion",
            field=models.BooleanField(default=False),
        ),
    ]
