# Generated by Django 5.1.3 on 2024-11-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="created_at",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="added_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
