# Generated by Django 5.1.3 on 2024-11-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cart_remove_cartitem_added_quantity_and_more"),
        ("cart", "0003_cartitem_session_key_alter_cartitem_user_and_more"),
    ]

    operations = []
