# Generated by Django 5.1.3 on 2024-11-20 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_order_orderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_holder", models.CharField(max_length=100)),
                ("card_last_four", models.CharField(max_length=4)),
                ("card_expiry", models.CharField(max_length=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("payment_status", models.CharField(default="PENDING", max_length=20)),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="cart.order"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["transaction_id"], name="cart_paymen_transac_e3691a_idx"
                    )
                ],
            },
        ),
    ]
