# Generated by Django 5.1.3 on 2024-11-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Tarjeta de crédito/débito"),
                    ("cod", "Contrareembolso"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(
                choices=[
                    ("free", "Envío estándar (3-5 días)"),
                    ("express", "Envío express (24-48h)"),
                ],
                max_length=10,
            ),
        ),
    ]
