# Generated by Django 5.1.3 on 2024-11-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_ciudad_envio_order_codigo_postal_envio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("paid", "Pagado"),
                    ("shipped", "Enviado"),
                    ("delivered", "Entregado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
