# Generated by Django 5.1.3 on 2024-11-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="descuento",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="en_promocion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="precio_promocion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
