# Generated by Django 5.1.3 on 2024-11-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_descuento_product_en_promocion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="promocion",
        ),
    ]
